### ISSUE TITLE
Configure a modern version of the Asciidoctor Maven Plugin when a Maven project depends on Spring REST Docs

### ISSUE THREAD

**Issue by dashaun** [spring-io/start.spring.io#1084]
See also: https://github.com/spring-projects/spring-restdocs/issues/878

**Comment by wilkinsona** [comment]
There's no 2.2.1 version of the Gradle plugin so we should revert that part of https://github.com/spring-io/start.spring.io/commit/6a3535023b5b65c8f382f2055a319b3d4bab64e7. We should probably also take a look at #676 as it's long over due. In fact, it may be better just to do that rather than dropping back to 1.5.8 which may not even work.
