### ISSUE TITLE
Quickstart tutorial fails at several points

### ISSUE THREAD

**Issue by Lobz** [spring-io/start.spring.io#1088]
This issue refers mainly to problems in the quickstart tutorial found [here](https://spring.io/quickstart), so if this is the wrong place to report them please forward me the right one. I'm opening this issue because it took me over an hour to understand why I couldn't get the Hello World working, and I believe that is terrible for a tool that should make coding easier.

For context, I have worked with Java in the past, but never had much experience with Maven, and haven't kept up with the language for the last 7 years. I'm using a newly installed Windows 11 and VS Code with Powershell, and before following the guide I had not installed any software related to Java or Spring. I'm gonna list the errors I ran into in the order I ran into them, ok?

1.  `mvnw is not recognized as a command` case a: the default project actually uses gradle and not maven, so the mvnw executable didn't exist. The guide should make it clear we have to download the Maven version, or indicate where we should use a different command.
2. `mvnw is not recognized as a command` case b: I'm using Powershell and it doesn't load local commands by default, so I had to use the command `.\mvnw` or `./mvnw` instead.
3. Although the guide suggests installing JDK 8 or 11, the project is set to target release 17. Therefore, if you have only JDK 11, you get this error: `Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project demo: Fatal error compiling: error: invalid target release: 17 -> [Help 1]`
4. After installing JDK 17, I reran the command, and got a positive result and return to terminal. I clicked the link and got a 404 error.
5. I feared the error might be due to a lack of a Server, so I installed Wampp. I reran the command, the program kept running (no return to terminal) and on clicking the link I got... a slightly different 404 error... wait I just noticed I forgot to edit back the files after downloading different versions to correct the previous mistakes... Let me just... Ok after correcting all these mistakes, everything works. 

I'm not quite sure if Wampp was necessary or not, nor if it was supposed to be necessary or not. I also installed and then unistalled both Maven and Gradle at some point, because the guide didn't make it clear if I needed them, and at that point I didn't trust the guide anymore because of errors 1 to 4.

**Comment by bclozel** [comment]
Hello @Lobz, thanks for reaching out.
spring.io is managed in a different place, but we'll keep this issue here anyway.

I'm sorry you had to go through this experience. This is a combination of two things: we recently released Spring Boot 3.0 (which now requires Java 17) and switched to Gradle as a default build tool for projects created on start.spring.io in #1012.

We need to update the quickstart with these two in mind, also making more friendly to Windows users. We're going to update the spring.io website infrastructure soon as well, so we need to track this change. Let me sync with @oodamien and I'll get back to you here.

**Comment by bclozel** [comment]
We've [slightly updated the quickstart page](https://spring.io/quickstart) to fix the main issues. Screenshots are not yet in sync with those changes but this should be a less confusing experience for newcomers. I'm leaving this issue opened for now to ensure that changes will be ported to the new application.

**Comment by lowell1** [comment]
Hello, I had the same problem and I was able to fix it with these steps.

1. Install java 17
2. run mvn clean
3. run mvn package (not sure if this was necessary)
4. then run mvn spring-boot:run

I just used regular mvn because the script didn't work. I am on Linux though not Windows. Hope this helps if not check out this article. https://www.codejava.net/tools/maven/fix-error-invalid-target-release

P.S. I'm brand new to all of this stuff so I don't really know what these commands do. I just know it was the only thing that fixed the problem for me lol.

**Comment by bclozel** [comment]
@lowell1 in your case, maybe another Java version was installed by default on your OS and was used by the `$JAVA_HOME` env variable, which is picked up by both maven and the wrapper. Without knowing how the script didn't work, I don't know how to improve the quickstart guide. If you're finding that managing java on your OS is challenging (as the java versions provided with the package managers aren't always the best...), you can look into tools like [sdkman!](https://sdkman.io/) to make your life easier.

I'm closing this issue now as we've ensured that the changes are also made on the upcoming new version of the site.
