### ISSUE TITLE
Eureka server needs jaxb-runtime (JDK 11+)

### ISSUE THREAD

**Issue by dsyer** [spring-io/start.spring.io#119]
In Java 12 (11 or above) a user that creates a Eureka server has a bad experience because it fails to start owing to the JAXB stuff being dropped from the JDK. We documented the fix in Spring Cloud user guide some time ago, but I guess now maybe we need to add jaxb-runtime to the generated project if user selects `dependencies=cloud-eureka-server`.

**Comment by snicoll** [comment]
> I guess now maybe we need to add jaxb-runtime to the generated project if user selects dependencies=cloud-eureka-server.

We've had a similar problem with Hibernate back then and decided to add JAXB to the JPA starter so that it is transparent to all users (not only those that are creating an app from start.spring.io). Eventually, community feedback led the Hibernate team to add the dependency to Hibernate itself. 

I don't think going here is the proper course of action and, considering the starter is maintained by us, I'd recommend adding JAXB there the same way we did.
