### ISSUE TITLE
Configure a KafkaContainer when Kafka and Testcontainers are selected

### ISSUE THREAD

**Issue by rajadilipkolli** [spring-io/start.spring.io#1226]
Raising issue as per conversation with @snicoll in twitter, Can you please guide me where to fix. I would love to contribute to it.

**Comment by snicoll** [comment]
So I am told we've got issue finding a Kafka image that works with random ports, which is why it wasn't added for our docker compose support. However, Testcontainers seem to support it so we could give that a try.

If you'd like to contribute that, you can create a `ServiceConnectionsCustomizer` bean in `io.spring.start.site.extension.dependency.DependencyProjectGenerationConfiguration` that contributes the image definition when `testcontainers` and `kafka` are selected. Search the codebase for such type for an example.

Let me know if you'd be interested to take this one. Thanks!

**Comment by eddumelendez** [comment]
Hi, @rajadilipkolli wonder if you will be able to address this issue or need help. I'd be glad to help or anyone else that is interested or submit it by myself if you can't. Please, LMK.

**Comment by snicoll** [comment]
@rajadilipkolli how is it going? Do you still want to contribute?

**Comment by rajadilipkolli** [comment]
Hi @snicoll , I am busy in my current assignment you can pass this on to others.  Sorry that I couldn't take it up and respond on time

**Comment by eddumelendez** [comment]
@snicoll should we consider it when kafka stream is selected too?

**Comment by snicoll** [comment]
If Spring Kafka isn't around, then none of the connection details stuff is going to kick in.
