### ISSUE TITLE
What is the proper argument for java for starter.zip?

### ISSUE THREAD

**Issue by sproshev** [spring-io/start.spring.io#1243]
Hi!
I'm requesting initial application zip using the following link:

https://start.spring.io/starter.zip?type=gradle-project-kotlin&platformVersion=2.7.13.RELEASE&groupId=com.example&artifactId=demo4&name=demo&version=0.0.1-SNAPSHOT&language=kotlin&packageName=com.example.demo&javaVersion=11&packaging=jar&description&dependencies=data-r2dbc&dependencies=data-mongodb-reactive&dependencies=kafka&dependencies=data-jdbc&dependencies=testcontainers&dependencies=amqp&dependencies=kafka-streams&dependencies=oauth2-client&dependencies=activemq&dependencies=web&dependencies=flyway&dependencies=data-mongodb&dependencies=webflux&dependencies=thymeleaf&dependencies=security&dependencies=data-jpa&dependencies=liquibase

But still receiving build.gradle.kts with java 17, could you please help here?

**Comment by bclozel** [comment]
The version spec is wrong for two reasons:

* version `2.7.13.RELEASE` doesn't exist
* the proper query parameter is `bootVersion` (try `curl https://start.spring.io` to see the docs)

As a result, the service is ignoring this argument and is using the default, which is the latest supported version (3.1.1 at this time). Because the Spring Boot 3.x generation has been selected, you're getting the following warning in the `HELP.md` file:

```
# Read Me First
The following was discovered as part of building this project:

* The JVM level was changed from '11' to '17', review the [JDK Version Range](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions#jdk-version-range) on the wiki for more details.
```
