### ISSUE TITLE
Wrong Implementation Of Resilience4J via Spring Cloud Circuitbreaker Added When Adding Spring Cloud Gateway

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-io/start.spring.io#1367]
If you create a new project with Spring Cloud Gateway and Resilienc4J via Spring Cloud Circuitbreaker, Initializr adds the blocking version of Resilience4J instead of `spring-cloud-starter-circuitbreaker-reactor-resilience4j`.

If however you add Spring WebFlux and Resilience4J Initializr correctly adds the reactive implementation.

**Comment by wilkinsona** [comment]
I suspect this may be a broader problem than just Cirtcuitbreaker. Am I right in thinking that any dependency with a reactive variant should use that variant when Gateway's selected?

**Comment by ryanjbaxter** [comment]
Yes, currently the Gateway is reactive only.

**Comment by wilkinsona** [comment]
The fix is wrong as Gateway isn't reactive-only. For example, if the servlet-based Spring Web dependency is added, the Gateway dependency is automatically switched to `spring-cloud-starter-gateway-mvc`. With the change in 05dcb34 we now get the reactive version of Resilience4J when it should be the blocking version.

**Comment by wilkinsona** [comment]
After some discussion with @snicoll, we don't think there's a perfect way for us to tell what sort of Gateway (reactive or blocking) the user wants. We've had similar problems with Mongo, Cassandra, and so on and have resorted to having two entries for them. We think that doing the same for Gateway is the best route forward. One entry will add `spring-cloud-starter-gateway` and will have the reactive facet. The other will add `spring-cloud-starter-gateway-mvc` and will not have the reactive facet.

**Comment by ryanjbaxter** [comment]
Ah yes, with our release we now have an MVC starter.  However that is only present in 2023.0.x.  And initializr currently only adds `spring-cloud-starter-gateway`.

**Comment by ryanjbaxter** [comment]
Ah OK, thats good.  Then yeah I think having 2 entries makes sense then.

**Comment by wilkinsona** [comment]
The proposed changes are in [this branch](https://github.com/wilkinsona/start.spring.io/tree/gh-1367). It splits Gateway into two entries, `Gateway` and `Reactive Gateway`. The latter is annotated with the `reactive` facet so that selecting it will switch dependencies like Circuitbreaker to their reactive variants. The entries are named `Gateway` and `Reactive Gateway` rather than something like `Blocking Gateway` and `Gateway` for consistency with other similar pairs of entries where it's the reactive variant that has the longer name such as `Spring Data Reactive Redis` and `Spring Data Reactive Couchbase`. The `Gateway` entry, which maps to `spring-cloud-starter-gateway-mvc`, is only available with Boot 3.2+.
