### ISSUE TITLE
Upgrade to Wavefront for Spring Boot 3.2.0

### ISSUE THREAD

**Issue by oppegard** [spring-io/start.spring.io#1381]
Please bump  wavefront-spring-boot-bom and wavefront-spring-boot-starter to 3.2.0, which supports Spring Boot 3.2.

**Comment by jonatan-ivanov** [comment]
Hi,

In order to make this simpler to the users, can we consider re-adding the wavefront starter to initializer? Right now users need to add it manually if they want to try the freemium cluster. It would be great if this could work out of the box for initializer-generated projects.

/cc: @shavidissa @snicoll @mhalbritter

**Comment by mhalbritter** [comment]
Yeah, we're going to add the starter.
