### ISSUE TITLE
Spring Boot 3.3.0-SNAPSHOT did not work

### ISSUE THREAD

**Issue by donhuvy** [spring-io/start.spring.io#1389]
![image](https://github.com/spring-io/start.spring.io/assets/1328316/2288054b-8d72-41cd-a93a-1384843cd16e)

[demo.zip](https://github.com/spring-io/start.spring.io/files/13881937/demo.zip)

![image](https://github.com/spring-io/start.spring.io/assets/1328316/b72aa09b-5a14-49ba-9c8f-0473e3bf1756)

![image](https://github.com/spring-io/start.spring.io/assets/1328316/798d2a56-fc5b-45fa-a868-2b7276314649)

**Comment by wilkinsona** [comment]
I cannot reproduce this. I would expect the error message to list the plugin repositories that were tried. They are configured in `settings.gradle` that you have not shared. Even with nothing configured there, Gradle's plugin portal will be used by default. As the error message suggests, please run with `--info` or `--debug` to investigate the problem. If you share the output with us, please do so as text rather than as a screenshot. Also, if it's `--debug` output, please check that it does not contain any secrets.

**Comment by wilkinsona** [comment]
I've just noticed the `demo.zip` link in between the two screenshots. Sorry for missing it earlier. Unfortunately, it does not reproduce the problem. It would appear that it's specific to your environment or how you are running the build. If you use one of the suggestions in the error message and identify that the problem is somehow caused by start.spring.io, please share that information with us and we can re-open the issue and take another look.
