### ISSUE TITLE
Configure compiler to use -parameters flag

### ISSUE THREAD

**Issue by rwinch** [spring-io/start.spring.io#1453]
I think that it would be valuable if generated projects were automatically configured (in Gradle & Maven) to use the `-parameters` flag since [Spring Framework 6.1 removed support for `-debug` fallback](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#parameter-name-retention).

**Comment by rwinch** [comment]
Can it be updated to work with the IDEs as well?

**Comment by wilkinsona** [comment]
We configure Maven's compiler plugin and Gradle's `JavaCompile` tasks to compile with parameter information. Getting that information out of the build system and into the IDE is out of our control. If it isn't working, it should be reported to the IDE developers.

**Comment by rwinch** [comment]
That's disappointing. I guess I thought that if the build tool could be configured, then the IDE could be too

**Comment by wilkinsona** [comment]
It should work out of the box with IntelliJ as it delegates compilation to Gradle and all of Gradle's configuration then applies. If you're not delegating to Gradle then I think https://youtrack.jetbrains.com/issue/IDEA-154038/IDEA-doesnt-respect-Gradle-compiler-settings is the relevant issue. On the Eclipse side, I think https://github.com/eclipse/buildship/issues/1070 is the relevant issue.

**Comment by wilkinsona** [comment]
>  I guess I thought that if the build tool could be configured, then the IDE could be too

We might be able to configure Eclipse from with Boot's Gradle plugin. I'm not sure that there's anything we could do on the Maven side. Reading around, I don't think there's anything we can do for IntelliJ with Maven or Gradle that would work broadly enough. Given all of these caveats, I think this really ought to be fixed in the IDEs or their plugins so that everyone can benefit from build system compiler args being honoured by the IDE.
