### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by mhalbritter** [spring-io/start.spring.io#1604]
The project can't be built on Windows. I've added [a Windows CI](https://github.com/spring-io/start.spring.io/actions/workflows/build-on-windows.yml), which is currently failing.

**Comment by Jayanta0123** [comment]
@mhalbritter, 
I could see the all the differences in expected vs actual in the failed tests are with the whitespaces only. 
![image](https://github.com/user-attachments/assets/0d3919b0-4708-4ca8-a461-65a9230336e6)

All the 6 tests within that particular clas **TestcontainersProjectGenerationConfigurationTests** are failing, and reasons of failure is the same for all.

**Comment by Jayanta0123** [comment]
@mhalbritter, @ngocnhan-tran1996 
 
Pls note, the issue is resolved now from the windows build point of view. But one has to add the build option `spring-javaformat:apply` on the build option. I prefer this to be added in `pom.xml` in a future boot-release. Thanks. 

![image](https://github.com/user-attachments/assets/5f4a1f97-441d-4e17-9545-2417f1dbfc5e)

**Comment by mhalbritter** [comment]
Hmm, what do you mean?

The CI on Windows now passes: https://github.com/spring-io/start.spring.io/actions/runs/11212213990/job/31162758346

**Comment by mhalbritter** [comment]
Fixed by https://github.com/spring-io/start.spring.io/pull/1605, thanks @ngocnhan-tran1996!
