### ISSUE TITLE
Otlp metrics entry with Testcontainers and Docker Compose

### ISSUE THREAD

**Issue by eddumelendez** [spring-io/start.spring.io#1639]
otlp-metric has been added as a entry. Spring Boot supports Service Connection for [Grafana LGTM Stack](https://github.com/grafana/docker-otel-lgtm) and [OpenTelemetry Collector](https://hub.docker.com/r/otel/opentelemetry-collector). IMO, generating a test application with Grafana LGTM Stack would be much better because besides providing the OpenTelemetry collector it offers storage for metrics, tracing and logs and the Grafana dashboard.

I can contribute with this.

P.S: should also a otlp traces entry be added?

**Comment by mhalbritter** [comment]
Hey @eddumelendez, we talked about that and we don't think that having the OpenTelemetry collector in Docker Compose / Testcontainers would be valuable, because it has no UI. Also, we don't want to express an opinion on which backend you should use. For that reason we won't include a Grafana LGTM stack when selecting OTLP traces.
