### ISSUE TITLE
Generated Maven project does not process Lombok annotations when compiling with Java 23

### ISSUE THREAD

**Issue by lwiddershoven** [spring-io/start.spring.io#1654]
Example project (reproduction): https://github.com/lwiddershoven/spring-boot-start-lombok-issue

# Problem

Lombok-generated methods are not found during maven compilation.

# Reproduction

A project is created in `start.spring.io`, using maven and Java 23, with as only dependency `Lombok`.

Then a normal Java class `SomeData` is added with the Lombok `@Data` annotation. One attribute, `id` is added
to this data class. This is then referenced/used in `SomeDataUser`. `mvn clean verify` will complain: 
```
[ERROR]   /.../lombok/src/main/java/com/example/bugs/lombok/SomeDataUser.java:[7,14] cannot find symbol
[ERROR]   symbol:   method setId(int)
[ERROR]   location: variable someData of type com.example.bugs.lombok.SomeData
```

```java
@Data
public class SomeData {
  private int id;
}
```

```java
public class SomeDataUser {
  void test() {
     var someData = new SomeData();
     someData.setId(1);
  }
}
```

# Expectation

I would expect that a freshly generated project with Lombok as a dependency would process annotations as part of the maven build.

# Fix

One can add
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>${maven-compiler-plugin.version}</version> 
  <configuration>
    <annotationProcessorPaths>
      <path>
          <groupId>org.projectlombok</groupId>
          <artifactId>lombok</artifactId>
          <version>${lombok.version}</version>
      </path>
    </annotationProcessorPaths>
  </configuration>
</plugin>
```
to the pom file. This enables annotation processing during the build.

**Comment by wilkinsona** [comment]
Thanks for the sample.

The problem's occurring because Java 23 disabled automatic discovery of annotation processors from the classpath. As an alternative to declaring annotation processor paths (which requires duplicating the Lombok version), you can set a property instead:

```
<maven.compiler.proc>full</maven.compiler.proc>
```

We should probably set this property automatically for projects using Java 23, Maven, and Lombok.

**Comment by lwiddershoven** [comment]
Thanks for the rapid response.

I have tried this and it does not seem to work for me. 
I will continue to look into it as this gives a great starting point.

pom.xml 
```xml
<properties>
    <java.version>23</java.version>
    <maven.compiler.proc>full</maven.compiler.proc>
</properties>
```

```sh
➜  lombok git:(main) ✗ java -version
openjdk version "23" 2024-09-17
OpenJDK Runtime Environment Temurin-23+37 (build 23+37)
OpenJDK 64-Bit Server VM Temurin-23+37 (build 23+37, mixed mode, sharing)

➜  lombok git:(main) ✗ mvn -version
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /Users/leon/.sdkman/candidates/maven/current
Java version: 23, vendor: Eclipse Adoptium, runtime: /Users/leon/.sdkman/candidates/java/23-tem
Default locale: en_NL, platform encoding: UTF-8
OS name: "mac os x", version: "15.1.1", arch: "aarch64", family: "mac"

➜  lombok git:(main) ✗ mvn clean   
...


➜  lombok git:(main) ✗ mvn verify
...
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project lombok: Compilation failure
[ERROR] /Users/leon/Downloads/lombok/src/main/java/com/example/bugs/lombok/SomeDataUser.java:[7,14] cannot find symbol
[ERROR]   symbol:   method setId(int)
[ERROR]   location: variable someData of type com.example.bugs.lombok.SomeData
[ERROR] 
[ERROR] -> [Help 1]
```

**Comment by lwiddershoven** [comment]
This is confirmed to work also for me. 

It does require an up-to-date spring-boot as the maven compiler plugin (provided by Spring Boots' parent) has to be 3.13.0, maybe 3.12.0 but higher than 3.11.0.

**Comment by wilkinsona** [comment]
Thanks for the confirmation. Spring Boot 3.3.x and 3.4.x should both be OK at they use 3.13.0 of the compiler plugin by default. Spring Boot 3.2.x and earlier are no longer supported by start.spring.io.

**Comment by mhalbritter** [comment]
No need to duplicate the Lombok version. This works fine:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <annotationProcessorPaths>
            <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
```

Maven documentation [says](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#optional-parameters):

```
<version>1.2.3</version> <!-- Optional - taken from dependency management if not specified -->
```

I lean towards adding the annotation processors explicitly instead of setting `<maven.compiler.proc>full</maven.compiler.proc>`.

**Comment by brenoepics** [comment]
This fixes the issues so u can compile your project created with start.spring.io but unfortunately, it does not work on IDE like IntelliJ IDEA  because it wont find the process annotator version.

![image](https://github.com/user-attachments/assets/6c0cc878-3dbb-422f-b6d0-ddf5efa0d810)

If I click on run button:

![image](https://github.com/user-attachments/assets/fe9b98af-9d37-4cef-843f-13dba5b985a6)

Not really an issue for me but new Spring Boot users may not know how to fix this or add version... 

(A friend approached me with this problem and he isnt familiar with maven, spring, ij... and had a hard time figuring out what was wrong)

**Comment by mhalbritter** [comment]
Thanks @brenoepics, you should report that to JetBrains.
