### ISSUE TITLE
AOP Starter not available to add as a dependency

### ISSUE THREAD

**Issue by marcinkunert** [spring-io/start.spring.io#180]
The AOP / Aspects starter seems to not be available to choose. Adding the dependency `spring-boot-starter-aop` manually works fine. Is this an intended behavior?

**Comment by wilkinsona** [comment]
It was intentionally removed as part of https://github.com/spring-io/start.spring.io/commit/fa647655f1362f08c083c40088a3b78a2366caa8#diff-5b750be579acca3f9e85b482abbb1f71. @bclozel may be able to provide some further details.

**Comment by bclozel** [comment]
@marcinkunert I think it was about the starter not being really popular, and being used for the wrong reasons (for a feature that is not related to that starter).
We can definitely reconsider this decision. Are you using this starter often? What's your primary use case for it?

**Comment by marcinkunert** [comment]
@bclozel my use case is a bit unusual. I've got a Spring programming course where I show different Spring libraries, how to setup and use them. One of them is AOP which i show the "non-boot-way" and also using boot and starter. It's fine for me if it won't make back into start.spring.io.

What I find inconsistent that there is a starter project not available at start.spring.io. It might be a good idea when deprecating projects, but if **spring-boot-starter-aop** is planned to be maintained than in my opinion it should be available at the starter generator. What would be an alternative way to find out the existence of this starter?

**Comment by bclozel** [comment]
I get it now, thanks for the clarification.

We're already a bit inconsistent here, mixing officially maintained starters with libraries and 3rd party starters (not making that difference obvious). Also, many valuable 3rd party starters are not listed on start.spring.io (for good reasons), they're [listed somewhere else](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-starters#starters).

I guess start.spring.io is not about listing all possible starters, but rather helping developers bootstrap a new project. I don't know how we could educate developers about types of dependencies listed on start.spring.io (official starter, library, 3rd party) or if it's valuable, and if we should provide a complete list somewhere independently.

**Comment by marcinkunert** [comment]
Let me explain my point of view, the decision is ofc up to you.

As a developer I would expect all the (official) starters to be on start.spring.io, simply because there is no reason why not (at least on the first thought). There is already a lot of them and no information that the list is limited. So I go to the search bar and type "aop" or "aspect" and there is nothing. At this moment I think there is no starter for that and I have to setup it manually.

One way to fix this would be to expand the "No result." message to sth like "No result. Consider checking the [community starters](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-starters#starters)". Or (in this case) "No result. Consider checking the [community starters](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-starters#starters) and [our official ones](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-starter) which didn't make it to the list."

I'm sorry for the exaggeration but the more I think of it the more it seems to be wrong.

**Comment by snicoll** [comment]
I understand where you are coming from but the argument of "everything must be there" is not what the service is all about. It's not a marketplace either so the lack of presence here doesn't mean what you think it means.  We're doing our best to rationalize what is required for a typical app to get started and writing a custom aspect is not part of that.

There is a separate history with this entry, our statistics showed the use of "aop" was crazy high as @bclozel mentioned (way too high for what it actually provides). We've tried to mitigate this by renaming the entry to "Aspects" and provide a better description. This helped a bit but a large portion of our user base still considered they had to select that entry to do use an aspect. 

I understand that this is breaking your course and I am sorry about that. Mentioning that the starter should be added rather than selecting the now-removed "Aspects" entry shouldn't be a big change hopefully.

**Comment by marcinkunert** [comment]
@snicoll Thanks for the answer. I understand now that the decision is well thought out. I'll adjust my course, thats not an issue at all. I just wanted to share my opinion on this.
