### ISSUE TITLE
Please add support for the Spring Cloud RSocket client

### ISSUE THREAD

**Issue by joshlong** [spring-io/start.spring.io#353]
Hi, would you please support specifying the `spring-cloud-rsocket-client` on the Initializr:

```   <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-rsocket-client</artifactId>
        </dependency>
```

it in turn requires 

```   <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-rsocket-dependencies</artifactId>
                <version>${spring-cloud-rsocket.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

in the `dependencyManagement` section. The property to use `<spring-cloud-rsocket.version>0.2.0.BUILD-SNAPSHOT</spring-cloud-rsocket.version>`. This works with the latest GA release of Spring Cloud Hoxton. 

Because it is GA, it'll require access to the Spring Snapshots repository. 

thanks in advance for your consideration.

**Comment by snicoll** [comment]
@joshlong thanks for the suggestion but such low-level details on how the service should operate is not the information that we need. 

Perhaps you've missed it but there is a [new entry proposal](https://github.com/spring-io/start.spring.io/issues/new?labels=type%3A+entry-upgrade&template=add-entry-proposal.md) template for requesting a new entry. I agree that we can shortcut most of it for internal dependencies so I am ok for not using it. However, we do need some information from the team handling the project:

* Sensible one-liner description
* Supported Spring Boot version(s) (and mapping if there is more than one)
* A link to a sample that showcases how this entry can be used (minimal getting started)
* Link to reference doc

In general, we prefer that the team who manages the feature suggests the addition. Can you please reach out to them so that we get the information that we need? Thank you.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
