### ISSUE TITLE
ConcurrentModificationException in integration tests

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#522]
CI builds fail from time to time with 

```
java.util.ConcurrentModificationException
	at io.spring.start.site.ProjectGenerationIntegrationTests.projectBuilds(ProjectGenerationIntegrationTests.java:170)
```

It happens more often on my box.

**Comment by mkrzywanski** [comment]
It seems that because of `@TestInstance(Lifecycle.PER_CLASS)` there is one test instance shared between parametrized test methods invoked from different threads. And those threads invoke methods on shared instance of `ProjectGenerationInvoker` which uses `LinkedHashMap` internally which is not thread safe. Specifically `computeIfAbsent` is invoked on this map and threads modify the internal state of map after applying the remapping function. A workaround would be to set `@TestInstance(Lifecycle.PER_METHOD)` so every thread has it's own instance of test class.Or change the implementation of `ProjectGenerationInvoker` to use thread safe map (but this cannot be done in this project I believe). I can submit a PR for that if you want.

**Comment by snicoll** [comment]
@mkrzywanski great detective work. I've created https://github.com/spring-io/initializr/issues/1124

If you can submit a PR that would be great!

**Comment by snicoll** [comment]
The fix in https://github.com/spring-io/initializr/pull/1125 seems to have fixed this one. Thanks again @mkrzywanski!
