### ISSUE TITLE
When spring-boot-configuration-processor is a dependency exclude it automatically in spring-boot-maven-plugin's configuration

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#528]
As suggested by @mkheck, when a Maven project depends upon `spring-boot-configuration-processor`, we could automatically configure the following exclusion that's described [in the reference documentation](https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/htmlsingle/#configuration-metadata-annotation-processor-setup):

```xml
<project>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by snicoll** [comment]
Blocked by #1165

**Comment by mkheck** [comment]
If I'm reading the other issue correctly and also correctly grokking the implication, there is already an exclude being processed that precludes this being added, per the docs?

**Comment by snicoll** [comment]
I don't know what you mean by "other issue" and "per the docs", I am afraid. If you're talking on the 2.4 feature that we flag certain annotation processors to exclude them automatically, this is a 2.4+ feature only and the customiser [handles that](https://github.com/spring-io/start.spring.io/commit/9d2e2d63b844a3e40f96e51d0ea06cef477da86e#diff-934576e6feb7123603b961c1c45ffcbb0339d25e9c2d3f907eb5d3b652251c67R39-R43).

**Comment by mkheck** [comment]
"Per the docs" refers to the documentation @wilkinsona links in the issue in which it states that the developer must manually exclude the `spring-boot-configuration-processor` from the Maven plugin. The other issue is the one you reference directly above: https://github.com/spring-io/initializr/issues/1165

Creating a Boot 2.4.1 project with the configuration processor using Initializr doesn't show the exclusion Andy and I discussed as captured in this issue. This is the plugin section from the Initializr-generated POM for 2.4.1:

```
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
```

The question really revolves around this:

Since we state this in the docs that...

_If you have defined @ConfigurationProperties in your application, make sure to configure the spring-boot-maven-plugin to prevent the repackage goal from adding the dependency into the fat jar:_

```
<project>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

...couldn't we/shouldn't we do that automatically when generating the build file?

**Comment by mkheck** [comment]
@snicoll I believe some of the confusion is over the docs vs. the apparent reality (?) of 2.4+, as the current (2.4.1) docs still show the same set of steps for devs to take when using the configuration processor, implying it's still necessary.

**Comment by snicoll** [comment]
Thanks for the additional context.

> Creating a Boot 2.4.1 project with the configuration processor using Initializr doesn't show the exclusion Andy and I discussed as captured in this issue

It does not because this particular annotation processor has extra metadata and we filter it out automatically. See https://github.com/spring-projects/spring-boot/issues/22036. If you select `lombok` that is the other annotation processor our production instance defines, you'll see the exclude. Alternatively, you can take that existing setup and chose another Spring Boot version (pre 2.4) and you'll see the exclude as well. All that setups, including the one you've described above does not include the annotation processor in the repackaged archive.

>  I believe some of the confusion is over the docs vs. the apparent reality (?) of 2.4+, as the current (2.4.1) docs still show the same set of steps for devs to take when using the configuration processor, implying it's still necessary

We're on the same page now. Yes, the doc should have been updated, thanks for spotting that. I've created https://github.com/spring-projects/spring-boot/issues/24498

**Comment by mkheck** [comment]
Makes sense. Thank you @snicoll, this is good!
