### ISSUE TITLE
Gradle project with Kotlin and Spring REST Docs does not build

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#581]
See https://github.com/spring-projects/spring-boot/issues/24272

**Comment by sdeleuze** [comment]
The `build.gradle.kts` is something like:
```kotlin
extra["snippetsDir"] = file("build/generated-snippets")

// ...

tasks.test {
	outputs.dir(snippetsDir)
}

tasks.asciidoctor {
	inputs.dir(snippetsDir)
	dependsOn(test)
}
```

@snicoll In the original issue you wrote:
> this includes a customization for the snippetsDir that looks incorrect with more recent Gradle version. We need to figure out why the integration test didn't caught that.

I have the same `Unresolved reference: snippetsDir` error  with Gradle 5.6.4 which the earliest minor that Spring Boot 2.4.0 supports, so I am not sure it is related to recent version of Gradle.

My guess is that `extra["snippetsDir"] = file("build/generated-snippets")` is fine but does not allow to write `outputs.dir(snippetsDir)` because `snippetsDir` variable does not exists. I am not sure what is the idiomatic configuration for Spring REST docs since its [reference documentation](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/) only document Gradle Groovy. Maybe @wilkinsona can give use some insights.

Notice I have also an additional error:
```
dependsOn(test)
                      ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                          public val NamedDomainObjectContainer<KotlinSourceSet>.test: NamedDomainObjectProvider<KotlinSourceSet> defined in org.gradle.kotlin.dsl
                          public val SourceSetContainer.test: NamedDomainObjectProvider<SourceSet> defined in org.gradle.kotlin.dsl
                          public val TaskContainer.test: TaskProvider<Test> defined in org.gradle.kotlin.dsl
```

**Comment by kedare** [comment]
Indeed there are both errors.
I found as a quick workaround to change 

```
extra["snippetsDir"] = file("build/generated-snippets")
```

to

```
val snippetsDir = file("build/generated-snippets")
```

I'm not really sure of the difference ?

And commenting the `dependsOn(test)` (that I am not using yet)

**Comment by mandrean** [comment]
I got around it by replacing the lines with:

```
val snippetsDir = file("build/generated-snippets").also { extra["snippetsDir"] = it }
```
and
```
dependsOn(tasks.test)
```

**Comment by eduardog3000** [comment]
spring-io/initializr#922 suggests

```Kotlin
val snippetsDir by extra { file("build/generated-snippets") }
```

as the idiomatic solution.

**Comment by Y-StrongBless** [comment]
spring官方就是一群见骂的胚子，这个问题从2.1就有了，就是不修复，看的我血压上升了

**Comment by mhalbritter** [comment]
I've fixed this problem. The build now reads:

```kotlin
extra["snippetsDir"] = file("build/generated-snippets")

tasks.test {
    outputs.dir(project.extra["snippetsDir"]!!)
}

tasks.asciidoctor {
    inputs.dir(project.extra["snippetsDir"]!!)
    dependsOn(tasks.test)
}
```

**Comment by sdeleuze** [comment]
Thanks for this fix @mhalbritter!
