### ISSUE TITLE
Upgrade to Azure spring 3.0.0

### ISSUE THREAD

**Issue by yiliuTo** [spring-io/start.spring.io#606]
Hi, the `azure-spring-boot-bom` of version 3.0.0 has been release to Maven: https://repo1.maven.org/maven2/com/azure/spring/azure-spring-boot-bom/3.0.0/. For 3.0.0, it supports Spring Boot 2.2.x and 2.3.x. Besides, we have modified the group-id from `com.microsoft.azure` to `com.azure.spring`, and also the artifact-id of 3 starters have been changed as below:
azure-active-directory-spring-boot-starter  --> azure-spring-boot-starter-active-directory
azure-storage-spring-boot-starter --> azure-spring-boot-starter-storage
azure-keyvault-secrets-spring-boot-starter --> azure-spring-boot-starter-keyvault-secrets

So could you help to upgrade the version of azure bom to the latest for Spring Boot 2.2.x and 2.3.x?
Thanks

**Comment by snicoll** [comment]
@yiliuTo thanks for the update and congratulations on the release.

Spring Boot 2.2.x is out of OSS support and has been removed from start.spring.io so that covers 2.3.x only at this point. I am little bit surprised that this new major release does not build against Spring  Boot `2.4.x`. I think it's very likely that it does work with Spring Boot 2.4, actually. Would it be possible for you to give that a try and setup a CI build for the project?

Also, switching to a new major release and  changing artifact names is disruptive and should not happen for users choosing a maintenance release of Spring Boot. As a user selecting Spring Boot 2.3.x, I don't except overnight to get a new major release of the Azure support. Right now, Azure is disabled for Spring Boot 2.4 onwards so enabling this new major there looks more suitable to me.

Have I missed something?

**Comment by yiliuTo** [comment]
Hi @snicoll , thanks for your quick reply. Yes, the latest release doesn't support Spring Boot `2.4.x` due to some conflicts on netty and reactor libraries. But we plan to publish a new version of 3.2.0 this month(perhaps in 2 weeks) to support Spring Boot 2.4.x.

And for your concern on artifact names, due to that we bring lots of new features on `azure-spring-boot-starter-active-directory` in this release, so we hope developers could have access to it with Spring Boot 2.3.x. And is it possible to update azure-spring-boot-bom towards Spring Boot 2.3.x?

Thanks

**Comment by snicoll** [comment]
@yiliuTo thank you for helping us serving the latest and greatest on start.spring.io. Looking forward to `3.2.0` and offering support to Spring Boot `2.4.x` users.
