### ISSUE TITLE
Kotlin Projects with Gradle Groovy DSL

### ISSUE THREAD

**Issue by corneil** [spring-io/start.spring.io#641]
I still find the Kotlin DSL for Gradle a barrier compared to using the Groovy DSL.
Can we please have the option of choosing the DSL language when choosing Gradle builds?

**Comment by snicoll** [comment]
Thank you for the suggestion. This was requested before and declined and we haven't changed our opinion about it, see https://github.com/spring-io/initializr/issues/1171.

**Comment by dswiecki** [comment]
@snicoll @wilkinsona Do you consider restoring Groovy build.gradle support for Kotlin codebase ?. It turns out that there are few drawbacks of kts build files:
- IntelliJ IDEA IDE integration works awful with build.gradle.kts (sic!) 
- there's tons of bugs e.g https://youtrack.jetbrains.com/issue/KT-42950
- IDE not updating dependencies when build.gradle.kts changes
- IDE running a cached version of source files
- until the kotlin-gradle file support was introduced groovy-gradle one's were widely used with Kotlin
- some people may simply not want to switch to a new format when they use Groovy
It looks like working with build.gradle.kts is quite a pain in the neck for the moment and thus it would be nice to have a previous option available

**Comment by wilkinsona** [comment]
It sounds like you're having a rough time of it at the moment but hopefully things will improve. For example a fix for KT-42950 appears to be imminent

> until the kotlin-gradle file support was introduced groovy-gradle one's were widely used with Kotlin

I'm not sure I have understood this point. Before Gradle's Kotlin DSL was available the only choice was Groovy so it was inevitable that Kotlin projects would use the Groovy DSL at that point

> some people may simply not want to switch to a new format

This one cuts both ways. We've heard from people who prefer the Kotlin DSL and they would not want to switch back to Groovy.

start.spring.io is always going to be about opinions to some extent at least. Our opinion is that when you're writing in Kotlin, Gradle's Kotlin DSL is the best way to configure your Gradle builds. Some would have us using the Kotlin DSL for Groovy and Java projects as well but we choose not to do so as Eclipse's Kotlin support is poor. I can't see us changing our opinion on either count unless there's a dramatic improvement in Eclipse's Kotlin support and a dramatic deterioration in IntelliJ IDEA's Kotlin support.

**Comment by sdeleuze** [comment]
To complement what @wilkinsona said:
 - Indeed https://youtrack.jetbrains.com/issue/KT-42950 should be fixed in Kotlin `1.4.31` which has been released.
 - Please make sure to use Gradle 6.8.0+ since it provides a significantly better experience
 - If there are other serious issues, please report them to me and I will forward them to Kotlin team to make sure fix in priority if possible
 - Even if I agree that Gradle Kotlin DSL can be frustrating, I think it is the Kotlin standard widely adopted on Android side and with strong commitments from Google, Jetbrains and Gradle to improve it so this opinionated choice on start.spring.io makes totally sense from my point of view
