### ISSUE TITLE
Support DGS Framework (GraphQL) from Netflix

### ISSUE THREAD

**Issue by paulbakker** [spring-io/start.spring.io#720]
The DGS Framework is now fully integrated with Spring GraphQL! 

# Requirements
To ensure the ongoing health of the Spring Boot community, a starter that is included on
start.spring.io must meet the following requirements.

## Code of Conduct

We adhere to the Contributor Covenant code of conduct as well, as listed here: https://github.com/Netflix/dgs-framework/blob/master/CODE_OF_CONDUCT.md

## Well-established project with a vibrant community

Github: https://github.com/Netflix/dgs-framework (3k stars)
Docs: https://netflix.github.io/dgs/
Presentations: https://netflix.github.io/dgs/videos/

## Licence
Apache License 2.0: https://github.com/Netflix/dgs-framework/blob/master/LICENSE

Currently, no license dependencies to note: https://github.com/Netflix/dgs-framework/blob/master/NOTICE

## Issue Tracker URL
https://github.com/Netflix/dgs-framework/issues

## Continuous integration
https://github.com/Netflix/dgs-framework/actions

## Maven Central
https://repo1.maven.org/maven2/com/netflix/graphql/dgs/

[x] Starter and all of its dependencies are available on Maven Central.

## Configuration metadata
https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-boot-oss-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json

https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-extended-scalars/src/main/resources/META-INF/additional-spring-configuration-metadata.json

https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-boot-micrometer/src/main/resources/META-INF/additional-spring-configuration-metadata.json

[x] Starter provides metadata, including documentation, for all its configuration
properties.

## Version mappings
Spring Boot 3.x (building against 3.2 currently).

## Links to additional resources

* Reference documentation: https://netflix.github.io/dgs
* Sample: https://netflix.github.io/dgs/examples/

**Comment by rstoyanchev** [comment]
@paulbakker, thanks for raising this.

Recently Spring GraphQL moved out of incubation and is now under [spring-projects](https://github.com/spring-projects/spring-graphql). We expect to publish 1.0 M1 this month, M2 before SpringOne in September, and we aim to enter an RC phase late this year. The Boot starter currently in Spring GraphQL will move into Spring Boot proper after the 2.6 release and will be included in 2.7. The starter will become available on start.spring.io as soon as the M1 release is out.

DGS and Spring GraphQL evolved independently and DGS is far ahead and more fully featured, but with both in perspective, we ought to consider how they can be complementary. The alternative of having two GraphQL starters on start.spring.io that both build on Spring is less than ideal from a community perspective.

We intend for Spring GraphQL to be a common foundation for all Spring applications, much like `graphql-java` is for Java applications. I realize in the short term this would be quite a diversion for DGS but we're very interested to collaborate in order to shape our APIs and create a good foundation. In the long run I think this would be a win for both of our objectives and for the community.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by paulbakker** [comment]
We have worked on a prototype to integrate DGS with Spring GraphQL. The details of the proposal are documented here: https://github.com/Netflix/dgs-framework/tree/spring-graphql-integration/graphql-dgs-spring-graphql-bridge.

@rstoyanchev we would like to talk this over further and decide if this is a good approach. I'm pretty excited about it at least, as it seems to be a good long-term strategy for integration.

**Comment by rstoyanchev** [comment]
Great, thanks for the proposal! It looks alright for a start. I'm up for a further discussion in more detail.

**Comment by paulbakker** [comment]
Updated the PR now that we have DGS / Spring GraphQL integraded.

**Comment by paulbakker** [comment]
Any news on this @bclozel ?

**Comment by bclozel** [comment]
Sorry about the delayed feedback @paulbakker , this is now done and live in production.
