### ISSUE TITLE
Gradle version catalogs

### ISSUE THREAD

**Issue by adityamparikh** [spring-io/start.spring.io#922]
For Spring Boot projects using Gradle could the projects be generated using version catalogs

**Comment by wilkinsona** [comment]
What catalogs would you expect them to use? Please note that Spring Boot [doesn't have one yet](https://github.com/spring-projects/spring-boot/issues/29588).

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by adityaparikh91087** [comment]
Apologies for the delayed response. 
Yes I meant the Gradle version catalogs available from 7.4+ where instead of having all the dependencies and version specified in the build.gradle file have them centralized in  libs.versions.toml where versions are in the [versions] section, dependencies are in the [libraries] section and the build.gradle specifies the libs.<library> syntax.

**Comment by wilkinsona** [comment]
I'm familiar with the concept of version catalogs. What I'm not sure about is which catalog you expect a generated project to use.

It sounds like you're proposing that, rather than using an existing catalog, one would be generated as part of generating a Gradle-based project. I don't think we'd want to do that as it would duplicate the contents of the `spring-boot-dependencies` bom that we already maintain as part of Spring Boot. Thanks anyway for the suggestion.
